### ISSUE TITLE
Sync doesn't work via Profile Register Form

### ISSUE THREAD

**Issue by EnesErtugrul** [lcdservices/CiviCRM-Group-Sync#5]
Hi,
I created profiles and Joomla registration is enabled for these forms. So users can register **without** Joomla's core registeration form but via CiviCRM's profiles forms.

But Sync doesn't work with this scenario. 

If user register with Joomla's core registration first, and then fills the profile forms Sync does work without problem.
I have Joomla 3.3.4 and CiviCRM 4.6.5 versions.

Thanks

**Comment by lcdservices** [comment]
Can you detail your setup a bit more --
The component syncs Joomla user groups and CiviCRM groups. I suspect in this case there is a bit of a race condition that we may not be able to work around: 

- the profile creates the contact record, the user record, then the connection between them
- if the contact is created and added to a group (either through the profile's advanced settings or by adding the group field to the profile), there is no user to sync with (yet)
- when the user is created and a group is auto-assigned (the default group), there is no connection to the contact yet, and so no way to sync

the sync triggers off two events: a civicrm contact being added/removed from a group, and the Joomla user account being saved. but a connection between the two (the contact and user) must exist in order for it to sync.

I don't think we can make it work in the case of a user account created from a profile, because that connection between the two can't be created until both separate records are created -- and at that point we've lost the events we trigger off.

**Comment by EnesErtugrul** [comment]
Actually I just realised that after I installed the component and set a rule, user is not assigned to the CiviCRM group (which used to work before). So as you said events are lost during the registration via profile form.

So I will get user registrations via Joomla core and then redirect them to the profile registration form. And there is no problem with that, your component works like a charm.

Thanks!
